### ISSUE TITLE
Specify -x in ldapsearch 

### ISSUE THREAD

**Issue by gittycat** [larrycai/docker-openldap#1]
I needed to specify -x to get your ldapsearch line to work:

```
ldapsearch -x -H ldap://192.168.59.103:63389 -LL -b ou=Users,dc=openstack,dc=org
```

Thanks for publishing this work.

**Comment by larrycai** [comment]
I put `-x` in end of my command. ;-).

Not expert for ldap, just works for me. Good to see it is useful for you.
